### ISSUE TITLE
TCI - Thetis does not recognise spots from SDC (Software Defined Connectors [BUG]

### ISSUE THREAD

**Issue by rsaue** [ramdor/Thetis-2.9.0#107]
Hi,
Using Thetis 2.9.0.8 pre and latest version of SDC (lw-sdc.com). 

**Problem**: Thetis does not put spots received from SDC via TCI on Thetis Panorama. 

Spots received from other sources through TCI, as Log4OM and SwissLOG, are shown on Thetis Panorama. 

Looking at the log of TCI traffic in Thetis shows that the only difference between sports from SDC and other sources, is that the spot command in sports sent from SDC uses lower case on the SPOT command, where other programs uses upper case.   As to the TCI specification from Expert SDR that the TCI implementation in Thetis is based on, TCI shall not be case sensitive (TCI protocol 1.9, section 4.1) I can not read code and can not tell if this is the answer to the problem.

![Thetis spot log](https://user-images.githubusercontent.com/22942440/227992847-784cb52c-2fb1-4df9-897b-079353cdd1dd.png)

73 de LB2EG Richard

**Comment by oe3ide** [comment]
The color code looks not correct. Highest value would be FFFFFF (16777215).

**Comment by oe3ide** [comment]
Correct, my bad. The value from SDC 4294967040 converts to argb #FFFFFF00, which is yellow. So that should not be the problem.

**Comment by ramdor** [comment]
fixed, it was indeed the colour value, failing to TryParse into a 32bit signed int.
