### ISSUE TITLE
[FEATURE] Export multimeters to database.

### ISSUE THREAD

**Issue by ydalton** [ramdor/Thetis-2.9.0#109]
**Describe the solution you'd like**
When you click "Reset Database" in the Setup window, if you have created multimeters, it removes them as expected. However, when you click "Export Database", it does not save the multimeters to the database, as when you import the database after resetting it, the multimeters do not return. Would you kindly add exporting the multimeters to the database?

**Additional context**
This is on Thetis v2.9.0.8 x64 pre-release.

**Comment by ramdor** [comment]
The multimeter config was being stored in the wrong table in the database. This has now been fixed and the DB import implemented. It also fixes the same issue with PA settings. NOTE: any meter config will be lost and user will need to re-layout/etc.
