### ISSUE TITLE
[BUG] Pure Signal Does not work after switching from Protocol 1 to 2

### ISSUE THREAD

**Issue by n1gp** [ramdor/Thetis-2.9.0#111]
**Describe the bug**
7000 DLE MKIII - recently received and works well with protocol 1. The protocol 2 firmware, Metis_Orion_MkIII_CV_P2_v2.1.12A.rbf, loads and runs on the MKIII hardware, but the Pure Signal will not function. It seems as if the radio does not monitor the signal like it does with protocol 1.

**To Reproduce**
Steps to reproduce the behaviour:
1. Use PS while running P1 F/W and note it working
2. Flash P2 firmware and rerun Thetis
3. Try running PS and note that it doesn't lock
4. Change the SetPK value to .2899 (or click on Default)
5. Note that PS now works

**Expected behaviour**
PS should work the same for P2 as P1

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows7/8.1/10/11/etc]

**Additional context**
In the PS menu while using P2:
Clicking on "default" , the SetPK value changed to .2899 from .4072.
PS now works correctly.

**Thetis should use .4072 for P1 and .2899 for P2**

**Comment by ramdor** [comment]
Hopefully now fixed.  The last successful started protocol is stored in the DB. Upon Thetis restart, this is checked against the protocol that is has now successfully started, and if different SetPK value is defaulted.
