### ISSUE TITLE
Blank meter containers at startup [BUG]

### ISSUE THREAD

**Issue by W2PA** [ramdor/Thetis-2.9.0#112]
Occasionally, at random times, on starting Thetis it comes up with one or more meter containers entirely black/blank. I can't reproduce this at will, but it happens every other day (approximately).

Some related observations:

1) When it happens, closing Thetis to restart it takes much longer than normal.  Instead of closing immediately, it takes on the order of 10 seconds or so to close.  This isn't long but it's quite noticeable.  On occasion, it won't close after an extended period and I have to kill it using Task Manager.  Sometimes when it does close on its own a remnant process is still lurking in the background and has to be killed with Task Manager.

2) Closing Thetis and restarting it brings back the formerly blank containers and everything's fine until it happens again.  I once had blank containers appear in two consecutive sessions, but that only happened once and it just took another down/up cycle to fix it.

3) When a blank container appears on startup, highlighting does not work for it.  The border on/off checkbox works and you can move it around.  But selecting other attributes has no effect, including background color (but I didn't try them all).

4) I seemed to be able to make it happen after roughly 7 or 8 bring up/down cycles but it varies.  When I made it occur to test out number 3 above, it happened to be the ANAN multimeter that was blank, so that's the only meter I tested it on.

5) It can happen with pinned (internal) or unpinned (external) containers.

6) I'm running with 10 containers, all on RX1.

I'm not familiar with the meter/container code at all.  But this feels a bit like a threading issue. Possible?

Additional context
ANAN-8000DLE, dedicated Ethernet connection, static IP addr, Thetis 2.9.0.8 x64 Protocol 2 v2.1.18 MM0LGE pre-release_2c, compiled by me after cloning the current repo, running on Windows 10 Pro on an ancient desktop with Intel i7-4820 CPU, 32GB RAM.

**Comment by ramdor** [comment]
can not replicate. Can you check ErrorLog.txt? Also, check that you have latest screen drivers.

**Comment by W2PA** [comment]
I kind of figured this would be hard to replicate. There are no entries in ErrorLog.txt more recent than April 2022.

Which screen drivers are we talking about?

Thanks.

**Comment by ramdor** [comment]
video card drivers, or if you have an embedded gpu, those drivers ;)  Also, check what other things are running, perhaps in the system tray, such as camera software, overlay stuff, osb perhaps, things like that, which may interact with directX in some way.

**Comment by W2PA** [comment]
I discovered that in Settings-Display-General, in the DirectX Display Settings panel, I had the thread priority pull-down set to "Below Normal" for some unknown reason.  I set it to "Above Normal" and now I can't make the blank containers appear after 30-ish startups.  So I think that fixed it. 

Please leave this issue open for a little while so I can continue to test.  I'll report back here.  If all is well maybe a posting in the Apache forum about this would be in order.  I did a basic search and didn't turn up anything about this particular setting.  There might be a posting but I didn't come across one.

**Comment by w-u-2-o** [comment]
FWIW I use "below average" and don't observe this problem.

**Comment by W2PA** [comment]
I'm guessing it's also because I'm using a below average computer (i7-4820), Scott.  I plan to upgrade and expect this sensitivity to thread priority will disappear.

**Comment by ramdor** [comment]
Very interesting chaps. The thread priority on the meter updates and the related renderers is set to Lowest, so if the system is struggling there could be a time when these may not show anything at all. Changing the thread priority in Setup->Display only changes the main spectrum renderer, and nothing to do with multi meters, which are fixed at Lowest.

However, the concern for me is the shut down delay, which perhaps implies some meter threads are being 'joined' to wait for them to finish (which eventually perhaps time out).

**Comment by W2PA** [comment]
Yes - it's hard to see how the priority on the main display would affect those meters.  I'm just glad it seems to have had a positive effect.

And the shut down delay happens every time there are blank meters, so the correlation is 100%.  One more detail: After clicking the red 'X' to shut down, Thetis continues to operate in receive until the delayed shut down happens.  Clicking the Power/Start button first doesn't affect the delayed shutdown.

**Comment by ramdor** [comment]
ok Chris, i'll also add a priority dropdown much like the Setup->Display so that it can be changed. Still, as you say, very odd that upping priority of main render display somehow impacts what is going on with the meters. I wonder if it is some issue at the directX/gpu level. The other interesting thing is that there are not more reports of it happening.

**Comment by mdblack98** [comment]
There's a rather long loop in the meter update logic which probably should yield the thread periodically.
Plus the way the meters are drawn is one point at a time which should probably build an object for a single call to be more efficient.

Mike W9MDB









On Monday, May 29, 2023 at 10:24:48 AM CDT, Richie ***@***.***> wrote: 







ok Chris, i'll also add a priority dropdown much like the Setup->Display so that it can be changed. Still, as you say, very odd that upping priority of main render display somehow impacts what is going on with the meters. I wonder if it is some issue at the directX/gpu level. The other interesting thing is that there are not more reports of it happening.

**Comment by W2PA** [comment]
> ok Chris, i'll also add a priority dropdown much like the Setup->Display so that it can be changed. Still, as you say, very odd that upping priority of main render display somehow impacts what is going on with the meters. I wonder if it is some issue at the directX/gpu level. The other interesting thing is that there are not more reports of it happening.

As I noted (confessed) earlier, Richie, it may be that my system is more sensitive to something since it's rather back-level.  But hopefully it'll lead you to eliminate a sensitivity point or improve the logic as Mike suggests.  

Still running today with no blank meters occurring.  Haven't tried reversing to Below Normal to make it recur.  Having too much fun with the 6m opening that's been going for the past couple of days.

**Comment by ramdor** [comment]
@mdblack98 the overall process time for drawMeters() is 'insignificant'. With **every** single meter item available added into a single container, the total elapsed time for a call is around 3ms on my machine. Meters are built with directX calls into a batch and then pipelined to the GPU with a single present call so not sure what 'meters are drawn is one point at a time' actually means tbh. The render loop is throttled to the quickest refresh time for a meter item, which can be as low as 50ms for 20fps.

**Comment by W2PA** [comment]
I did the following experiment. 

1. Returned the display priority to BelowNormal.  This resulted in my again getting blank meters twice in 12 starts of Thetis.
2. Edited MeterManager.cs to increase _meterThread to ThreadPriority.Normal.
3. Restarted Thetis 13 times (baker's dozen for good measure) with no blank meter occurrences - display priority was kept at BelowNormal.

Note that I did not change _dxRenderThread at all.  I was intending to try these one at a time.  But since changing _meterThread seemed to fix the problem, I didn't proceed.

Hope this is useful.

**Comment by W2PA** [comment]
I tried the opposite - set _meterThread back to Lowest and set _dxRenderThread to Normal.  Same behavior: no more blank meters.  I don't know what to conclude but it's pretty strange.

**Comment by ramdor** [comment]
can you try with both threads fixed to BelowNormal (_meterThread  & _dxRenderThread ) and see if you can get any blank meters?

**Comment by W2PA** [comment]
My comment above about it simply being less likely seems to be true.  I just had startup blank containers happen twice in succession using _dxRenderThread Normal and _meterThread Lowest.  For now I set them both to Normal.

So the problem does seem random, with the probability of occurrence decreasing as various thread priorities are adjusted.  I can't see any distinct pattern though.

Anything else specific to try?

**Comment by ramdor** [comment]
Try renaming the meter skin folder, so the images are not loaded. Shut Thetis down, rename, start it back up. Just want to test if it is an issue with gpu resources.

C:\Users\<user>\AppData\Roaming\OpenHPSDR\Meters
to
C:\Users\<user>\AppData\Roaming\OpenHPSDR\Meters2

**Comment by W2PA** [comment]
I'm running everything I'd normally be running while operating my station.  This includes DXLab, which itself is 6 applications, plus there are normally 4 Firefox windows open with a dozen tabs in each.  There is the VE7CC spotting cluster app which is non-graphical.  Then there is virtual ports (VSPE) to connect things, and MS Outlook.  That's most of it.  None of it is heavy graphically, except maybe some of the FF windows/tabs.

This always happens on startup, before the Power/Start button is clicked.

**Comment by ramdor** [comment]
100 containers, around 5-6 meters per container as a test. This is with the multimeter branch which has had a number of changes around MM threading. Although I am not expecting it to fix your issue tbh.

![image](https://github.com/ramdor/Thetis-2.9.0/assets/3124967/474144ed-cf82-4275-8f08-5c53fdfd6533)

**Comment by W2PA** [comment]
I have not pulled any updates from the multimeter branch for a while.  I'll do so and try it out when I get a chance.  Tnx.

That crazy quilt of meters looks like a sci-fi scene where multiple parallel universes suddenly collide.

**Comment by W2PA** [comment]
Update:
I recompiled after your recent changes on 6/2.  Since then (8 days as of now) I haven't run across a single instance of blank meters, even with no changes to thread priorities.

**Comment by mdblack98** [comment]
What changes on 6/2?
The git log shows Mar 17 as the last commit as does the commit log https://github.com/ramdor/Thetis-2.9.0/commits/master
commit 11d7a1cbb43291eda38dd120ff4c7176b21df73fMerge: 893764c 5679bb8Author: Richie ***@***.***>Date:   Fri Mar 17 02:36:17 2023 +0000
Mike W9MDB

 

    On Saturday, June 10, 2023 at 06:24:09 AM CDT, Chris Codella ***@***.***> wrote:  
 
 


Update:
I recompiled after your recent changes on 6/2. Since then (8 days as of now) I haven't run across a single instance of blank meters, even with no changes to thread priorities.

**Comment by W2PA** [comment]
I was referring to the multiMeter branch.

**Comment by mdblack98** [comment]
Thanks...wasn't aware another branch was in the works....
I'm running it now....
Mike W9MDB

 

    On Saturday, June 10, 2023 at 06:52:24 AM CDT, Chris Codella ***@***.***> wrote:  
 
 


I was referring to the multiMeter branch.

**Comment by ramdor** [comment]
> Update: I recompiled after your recent changes on 6/2. Since then (8 days as of now) I haven't run across a single instance of blank meters, even with no changes to thread priorities.

great new Chris. I hope to find a few hours tomorrow evening (sunday) to wrap a couple of things up and make a new release to master. The mm branch will then be closed off. 👍

**Comment by ramdor** [comment]
some fixes around the container/directX threading has seemingly resolved this. Will re-open if issue is reported again.
