### ISSUE TITLE
TCI - Thetis sends double legacy "clicked_on_spot" even when ESDR3 emulation is activated.... [BUG]

### ISSUE THREAD

**Issue by rsaue** [ramdor/Thetis-2.9.0#118]
Log4OM has in latest betal added populating callsign field when clicking on spot in panorama (TCI). Only the ESDR3 "rx_clicked_on_spot" is used in Log4om, which is ok with SunSDR radios using ESDR3 as ESDR3 sends both the legacy "clicked_on_spot", and the ESDR3 "rx_clicked_on_spot" when clicking on spot. 

In Thetis I can see in the code that there also "rx_clicked_on_spot" there, but when clicking on spots in Thetis it sends the legacy "clicked_on_spot" two times. even when I choose emulate ExpertSDR3 protocol in setup. 

I believe this is a bug. 

73 de LB2EG Richard

**Comment by ramdor** [comment]
Fixed. Both the legacy CLICKED_ON_SPOT and RX_CLICKED_ON_SPOT are now sent, the same as EESDR3. Log4OM now updates the callsign as expected.

Note: I could not replicate Thetis sending the legacy command twice, it only sends once, to each connected TCI client.
