### ISSUE TITLE
[BUG]ANAN-100D P1 Keying and Tune issues

### ISSUE THREAD

**Issue by kc9xg** [ramdor/Thetis-2.9.0#14]
**Describe the bug**
Thetis 2.9.0 22a

Thetis imported my previous database and appeared to work as intended.  
However, I soon discovered, if I have DUPE active and I hit the TUNE 
button the radio is modulated with TWO TONE.  Deactivate DUPE and TUNE 
button works as intended.

I reset the database to see if my imported database was causing the above
issue.  After reset, I selected ANAN-100D.  I then hit the Thetis power 
button the radio began keying up and down continuously.  If I power down 
with the Thetis power button and change the modulation from the default 
CW setting to USB, then power up again all is well at power up.

Bill KC9XG

**Comment by ramdor** [comment]
unfortunately I do not have a 100D to test it on. There have been no other reports of this as yet, or in the testing phase during 21k9. It might be a firmware issue?

**Comment by kc9xg** [comment]
Problem resolved by resetting power on the 100D radio

**Comment by ramdor** [comment]
> Problem resolved by resetting power on the 100D radio

ah ok Bill. Did you just power cycle the radio and it went away? Perhaps a F/W glitch?
