### ISSUE TITLE
CAT TX commands will not allow manual override [BUG]

### ISSUE THREAD

**Issue by w-u-2-o** [ramdor/Thetis-2.9.0#49]
**Describe the bug**

This is not a bug per se but perhaps it is best categorized that way.

The problem is that issuing CAT TX commands of the form ZZTX1; or TX; toggle MOX on but do not allow the operator to toggle MOX off from the UI. This situation persists even through a cycle of the "POWER" button in the UI.

This situation is dangerous as it does not allow the operator to easily recover from or override misbehaving rig control software.

**To Reproduce**
Steps to reproduce the behaviour:

1. Issue one of the above referenced CAT TX commands.
2. Attempt to put the radio back in a receive state by clicking on the MOX button in the UI.
3. Attempt to put the radio back in a receive state by clicking the POWER button and then clicking it again.
4. Note that both of the above actions will not terminate a TX state, it requires the issuance of a CAT RX command, either ZZTX0; or RX;.

**Expected behaviour**
A CAT instantiated TX state should be able to be manually overridden by using the MOX button in the main UI, or by using the POWER button to put the radio in a reset state.

**Comment by ramdor** [comment]
a cat instantiated TX will now be able to be terminated by the mox/power button. Note, if a manual mox (by clicking the UI button) is instantiated it can not be disabled via cat.

**Comment by ramdor** [comment]
fixed in 2.9.0.7 when released
