### ISSUE TITLE
Profiles don't change consistently

### ISSUE THREAD

**Issue by at6c** [ramdor/Thetis-2.9.0#56]
When going from one mode to another SSB to CW if I have NR2 select in SSB it no longer selected in CW.  Profiles have been previously setup for SSB and CW both in the Band Stack and transmit profiles.  I always operate with NR2 turned on and would like it to stay on.

Setup radio in SSB with Proflies and Bandstack saved with NR2 saved on.  Do the same for CW.  Go from CW to SSB and most of the time NR2 will be turned off.

**Expected behaviour**
If I save a profile or bandstack frequecny  I would like the NR2 setting to be saved in that Profile or Bandstack setting

**Screenshots**

**Desktop (please complete the following information):**
 Win10

**Additional context**
Thetis has worked great in all modes, contesting and DXing.  Best radio/software I have ever used in 50 years of hamming.  Many thanks.
73, George
W2GS
at6c@bellsouth.net

**Comment by oe3ide** [comment]
Afaik NR2 is not part of the TX-Profile. It makes no sense in the tx-profile (IMHO).
For the bandstack-profile/setting: it works as expected. If you store the bandstack with NR2 enabled, it recalls with NR2 enabled. If you switch to an entry with NR2 disabled, it disables NR2.

**Comment by ramdor** [comment]
similar reasons to #57 where a single profile is shared between cw/ssb/spec/dsb. It will need quite a big change. The main issue is recovering settings for the one time change over to a profile per mode system. I will put both #57 and this one as closed, but include on wish list.
