### ISSUE TITLE
[BUG] CW profile and VAC considerations

### ISSUE THREAD

**Issue by at6c** [ramdor/Thetis-2.9.0#57]
**Describe the bug**
When changing modes from SSB to CW VAC1 and VAC2 don't change with the mode.  In the CW GUI there is no profile selection box to select the CW profile.  I have to change the mode to SSB and then select the CW profile from the profile selection box to get the proper VAC selection.

**To Reproduce**
Setup a CW transmit profile using VAC1.  (for CW Skimmer)
Setup a SSB transmit profile using VAC2.  (for USB audio interface)
Set radio in SSB mode in SSB portion of the band.  Audio interface works FB.
Change to CW portion of the band.  Profile doesn't change to the CW profile.  if SSB mode is selected while still in CW portion of the band SSB profile is selected.  Have to change profile to CW while in SSB mode in CW portion of band.  There are a couple of other work arounds.

**Expected behaviour**
Would like VAC to change when going from SSB portion of the band to the CW profile.  If not possible have the transmit profile box be visible in CW mode so it is easier to the CW profile.  

This is also a problem when going from CW to SSB.  Mode will remain as CW and have to select SSB mode from the transmit profile box when in SSB portion of the band.

In both CW and SSB there are seperate profiles and the bandstack has been used to memorize parameters.  The Bandstack parameters are locked after they are memorized

**Screenshots**

**Desktop (please complete the following information):**
 Win 10

**Additional context**
73, George
W2GS
at6c@bellsouth.net

**Comment by ramdor** [comment]
couple of things :

a) currently usb/lsb/dsb/cwl/cwu/spec/drm  all use the same shared TX profile. AM/SAM/DigL etc have their own
b) TX profile is not stored in a band stack entry. The mode is stored in the BSE, and this indirectly selects which TX profile is used

It would be a quite a change to have each mode use its own TX profile, but would actually make sense and perhaps simplify things somewhat. LSB/USB for example would be set to the same txprofile, CW set to something else.

hmmmm.....

**Comment by ramdor** [comment]
this and #56 are related. Will feature on the wish list.
