### ISSUE TITLE
[BUG] S-Meter Calibration is lost on Thetis close or PC reboot

### ISSUE THREAD

**Issue by alexn3gx** [ramdor/Thetis-2.9.0#58]
**Describe the bug**
ANAN 7000DLE MKII (latest serial number) S-Meter calibration is lost on Thetis close. It looses the calibration and reverts to default as soon as the Thetis is closed. It defaults to show the reset status values (Typically an S-Unit more than what really is)

**To Reproduce**
1. Under Setup > Calibrate 
2. Click on Calibrate on selected frequency while injecting a known reference signal level such as -73dBm. (I use an ELECRAFT XG2 RF signal generator)
3. After It successfully completes the calibration routine, the signal meter shows -73dBM (or S-9)
4. See error next time you reboot or restart Thetis. It will revert back to -67dBm (S9+5) while using the same RF signal source.
5. It makes no difference if database was reset to default or newly created.

**Expected behavior**
The S-Meter on Thetis will revert to default settings: -67dBm (S9+5) using the same reference signal level at the chosen calibration frequency. Just as if RESET was pressed
(I use an ELECRAFT XG2 signal generator on ANAN 7000DLE MKII - latest serial numbers)

Expected Behavior:
The S-Meter on Thetis is expected to keep the calibrated parameters after PC reboot or Thetis restart and to show on the S-meter display the same signal level that it was used for its prior calibration when the reference signal is reapplied to the antenna port with no attenuation present.  A typical signal reference of -73dBm (or S-9) is commonly used.

**Desktop (please complete the following information):**
 - OS: [Windows 10 x64]
 - Software: Thetis v2.9.0.6 x64 (4/23/22)

**Comment by ramdor** [comment]
yes, s-meter calibration storage was unfortunately broken in 2.9.0.6. It will be fixed when 2.9.0.7 is released. I will leave this open until 2.9.0.7 hits so that others can read it.

Richie.

**Comment by w-u-2-o** [comment]
Interesting. I can't duplicate this behavior.

Windows 10 Pro, Thetis 2.9.0.6 x64, ANAN-8000DLE, Firmware 2.1.18

I cannot duplicate your problem. I just dragged out all of my calibration equipment and there is no problem with the level calibration on my installation.

FWIW: when calibrating, pay attention to the S-meter, not necessarily the panadapter. Calibrate in Sig Avg mode. Make your bandwidth 500Hz.

When looking at the panadapter, ensure that the detector mode is average, the zoom is all the way zoomed in (minimum bandwidth), and that the bin width is adjusted to maximum. This should get the S-meter and the S-meter within 1dB of each other.

**Comment by alexn3gx** [comment]
Scott,
The problem is not while calibrating the S-Meter on the ANAN, the problem
is Thetis remembering the calibration results which Richie confirmed.

Richie ***@***.***> Unsubscribe
9:19 AM (3 hours ago)
to ramdor/Thetis-2.9.0, me, Author

yes, s-meter calibration storage was unfortunately broken in 2.9.0.6. It
will be fixed when 2.9.0.7 is released. I will leave this open until
2.9.0.7 hits so that others can read it.

Richie.

**Comment by ramdor** [comment]
yes, unfortunately I removed a line accidentally.... fat finger issue ;)

rx_meter_cal_offset_by_radio[(int)current_hpsdr_model] = rx1_meter_cal_offset;  // MW0LGE_[2.9.0.7] re-instated

It is all to do with the save and reload. I am tempted to release a 2.9.0.7 without meters just to get a couple of things squared away.

Richie.

**Comment by ramdor** [comment]
@w-u-2-o if you had previously saved a calibration with an older version of the software then that will be read in and all will look fine. However if you re-calibrate and get a different offset then that wouldn't have been saved with 2.9.0.6.

**Comment by alexn3gx** [comment]
Understood, that's a true statement. Again, the intent here is to identify
software bugs, and if I had done it that way, I would never notice such
bugs.
Since I started using the PowerSDR in the early days of the Flex SDR-1000,
I learned from the Tortoise group that it's a good practice to start a
fresh database on every new release.

**Comment by ramdor** [comment]
closing, as it is now fixed, and will be resolved in 2.9.0.7 when released
