### ISSUE TITLE
[BUG] Thetis enters weird state after Tune with VFO just outside band edge

### ISSUE THREAD

**Issue by W2PA** [ramdor/Thetis-2.9.0#60]
**Describe the bug**
Triggered by Tune, Thetis enters a strange xmit-only state when the VFO line on panadapter is outside the band edge but CW offset would put the actual transmitted signal inside.

**To Reproduce**
Steps to reproduce the behaviour:
1) Start in CWU mode near a lower band edge.
2) Position the VFO cursor below the band edge but the VFO dial display frequency above it, i.e. the CW offset would put a CW signal just inside the band and the dial indicates you're within the band since it takes the CW offset into account.  Example: VFO A says 14.0003 and offset is 600Hz but the red VFO line is just below the band edge in the panadapter.
3) Hit Tune (TUN button).  An out-of-band warning window pops up.
4) Click OK and now Thetis is in a weird TX-only mode.  You can recover normal operation by re-starting Thetis or by cycling the MOX button or doing the same thing by hitting the CW key in Semi mode.  There may be other recoveries but I haven't searched for more.

**Expected behaviour**
The OOB warning properly takes into account the CW offset - i.e. in the above procedure, Tune would cause a carrier on the red-line VFO position, which is OOB, but in CWU it still lets you transmit a CW signal - all is well.  But it should not enter this weird transmit-only state after the OOB warning caused by the Tune button (step 3).

**Screenshots**
A screenshot wouldn't show anything additionally helpful.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro, version 22H2, build 19045.2364

**Additional context**
ANAN-8000DLE, dedicated Ethernet connection, static IP addr, Thetis 2.9.0.7 x64 Protocol 2 v2.1.18 MM0LGE pre-release, compiled by me after cloning the current repo.

**Comment by ramdor** [comment]
looks like this was introduced in 21d a long time ago. Will be resolved for eventual 2.9.0.7 release
