### ISSUE TITLE
[BUG] TCI - Frequency offset when using SDC (Software Defined Connectors)

### ISSUE THREAD

**Issue by rsaue** [ramdor/Thetis-2.9.0#62]
As described by IW7DMH with reference to TCIServer.cs https://community.apache-labs.com/viewtopic.php?f=9&t=4383&p=22227&hilit=sdc#p22227

Fixing this would make SDC http://lw-sdc.com more usable with Thetis. 

73 de LB2EG Richard

(edit: Fixed links)

**Comment by ramdor** [comment]
should now be fixed in 2.9.0.7 when released.
