### ISSUE TITLE
[BUG] CAT Command descriptions etc do not display in Cat Caommand tester

### ISSUE THREAD

**Issue by kc9xg** [ramdor/Thetis-2.9.0#67]
The Cat Command Tester does not display CAT command info.  You can test commands successfully, just can't view CAT Command info.
Bill KC9XG

**Comment by ramdor** [comment]
now shows the catstruct.xml in the grid view, will be in 2.9.0.7 when released.

![image](https://user-images.githubusercontent.com/3124967/210670578-df31becf-3558-4004-b7a3-d63221cafb54.png)
