### ISSUE TITLE
"keyboard" Spacebar functions not working until Setup form opened - when RX2 enabled or "-autostart" used

### ISSUE THREAD

**Issue by WD5Y** [ramdor/Thetis-2.9.0#77]
If you select PTT for spacebar and enable RX2, after startup, no ptt but open setup and hit ok - ptt works until you close rx2 and start over with setup form. This is the case with "-autostart" as well.

**Comment by ramdor** [comment]
mox/ptt 'radio' control was set to TRUE in setup designer so that when the DB was read, no change event would fire if it was enabled. This prevented any state change in console.cs. This has now been changed to false (the default console state), and when read in from the DB, will cause the radSpaceBarPTT_CheckedChanged event in setup.cs.

**Comment by ramdor** [comment]
works fine here Joe. With or without -autostart and with RX2.  Works if RX1 is TX vfo, and TX on B. Can't replicate here sadly. Perhaps something is conflicting in settings somewhere? Incidentally CTRL-M will do the same.

**Comment by ramdor** [comment]
vid, cant replicated it : https://youtu.be/PzozgllSvTM

**Comment by WD5Y** [comment]
I was checking more into this last night and found it had nothing to do with opening Setup, it looks like what’s happening is that either when you check rx2 or open Thetis with “-autostart” the Console loses focus, you can click on the console form and then all works fine. It also shows in that on some buttons you have to double click for them to take. 

Thanks,
Joe
WD5Y

**Comment by ramdor** [comment]
yes Joe, I mentioned focus in the video above. We can 'hook' the entire system using similar code to the mouse wheel stuff, however when you are tyring away in a logger, or other such software PTT will be happening, not ideal.  Nothing really to fix here, other than to make sure you have focus as you say. Closing this.

**Comment by WD5Y** [comment]
I understand, sorry for the confusion. It sure had me going for a while.

Thanks,
Joe

**Comment by WD5Y** [comment]
Ritchie,
I hope it's ok, I sent you an invite to my repository, I did get it set 
to private. Probably not, but if anything there for you please use. I 
did get one item added for Sigi, I added a spacebar function for vfoa_tx 
to vfob_tx.

Thanks,
Joe
WD5Y
