### ISSUE TITLE
CAT Commands for Frequency not working properly

### ISSUE THREAD

**Issue by devmrs** [ramdor/Thetis-2.9.0#83]
I just purchased a HobbyPCB Hardrock-500, It uses CAT control to select the proper band. Instructions say to go to **Cat Command screen in PowerSDR and check "Allow Kenwood AI Command".** The amplifier works fine unless you enter a frequency that ends in a zero. 

For example, if I enter the frequency 7.273.018 the Cat Control Data is: FA00007273018; (correct)
But, if I enter 7.273.020 the Cat Control Data is:                                       FA00000727302; (incorrect)
The proper CAT command should be                                                       FA00007273020; (Expected result)

If I enter a frequency of 14.280.009 the Cat Control Data is:                     FA00014280009; (Correct)
But, if I enter a frequency of 14.280.010 the Cat Control Data is:              FA00001428001; (Incorrect)
The Cat Control data should be:                                                                FA00014280010; (Expected result)

Frequencies are supposed to be 11 digits right justified in Hz. 1.428.001 Mhz vs 14.280.010 Mhz

**Comment by ramdor** [comment]
This is was fixed in version 2.9.0.1 22a, which came out on the 4th April 2022.  We are now on 2.9.0.6.  Try updating to a newer version and please let me know if you are having issues.

**Comment by devmrs** [comment]
Yes, I discovered the newer release and that corrected the issue.
