### ISSUE TITLE
Add FM demodulation limiter from Warren's code [FEATURE]

### ISSUE THREAD

**Issue by w-u-2-o** [ramdor/Thetis-2.9.0#84]
**Is your feature request related to a problem? Please describe.**

The FM demodulator in the WDSP library allows for a great deal of gain and dynamic range. At the same time, the dynamic range of the audio system in Thetis (and Windows) is not nearly as large. The optimum amount of gain for a signal that generates full quieting in the FM demodulator might be far too much gain when the demodulator only sees noise, or some combination of signal and noise. This can make it difficult to adjust the receiver for best performance with a variety of weak, intermediate and strong FM signals. There is also the challenge associated with folks who don't drive their FM modulators hard enough and transmit strong signals but with weak deviation (no surprise, since there doesn't seem to be a single amateur radio with a deviation meter).

**Describe the solution you'd like**

Warren Pratt, NR0V, has developed a patch for 2.9.0.6 that incorporates a limiter in the FM receive functionality that largely solves the problem described above.

**Describe alternatives you've considered**

None.

**Additional context**

Warren is not familiar with the Github commit process. Perhaps he could be assisted with that so the FM limiter code can be incorporated into this repo.

Thanks!

**Comment by ramdor** [comment]
has been added, and will be released as part of 2.9.0.7 at some point
