### ISSUE TITLE
N1MM Spectrum scope off by CW pitch on N1MM Spectrum Window[BUG]

### ISSUE THREAD

**Issue by W7GES** [ramdor/Thetis-2.9.0#89]
**Describe the bug**
Hi Ritchie,   

  Using Thetis v2.9.0.6 - Just noticed in CWU the N1MM Spectrum Display is off by the CW pitch.  If I tune a station that is on 21.022 and zero beat him the Thetis spectrum display will show the signal at 21.022.  The N1MM spectrum window will show the signal at 21.0226.

  This was an issue a long time ago in SSB but you fixed it.  I'm guessing there is somewhere in Thetis when creating the N1MM UDP stream needs the output frequency to show frequency - cw pitch.  

  I only noticed this as I was noticing the lids on 3Y0J frequency were offset on the N1MM display.  In a contest everyone slides up and down to get away from interference and doesn't park on a "zeroed out" frequency.

  I tried this on 7.043 CWU and CWL and the signal is right on in Thetis and is offset by the CW pitch in N1MM (higher or lower depending on whether I choose CWU or CWL).

**To Reproduce**
Steps to reproduce the behaviour:
1. Tune a CW signal.  Note the zero beat frequency in the Thetis spectrum.
2. Start or look at the CW signal on the N1MM Spectrum Display.
3. The display will be higher or lower offset based on your CW pitch.  Adjust CW pitch up and down and signal will move on N1MM spectrum scope.

**Expected behaviour**
Tune in a signal on Thetis CW Zero line and it will match on the N1MM Spectrum display.

**Screenshots**
Let me know and I will provide

**Desktop (please complete the following information):**
 - OS: [Windows11]

**Additional context**
None

Thank You!

George / W7GES

**Comment by ramdor** [comment]
fixed, and will be in next release.  Thanks for report George.

**Comment by W7GES** [comment]
Thank You!On Feb 6, 2023, at 10:25 PM, Richie ***@***.***> wrote:﻿
Closed #89 as completed.
