### ISSUE TITLE
Thetis startup in Collapsed view issue, Expanded view controls showing.

### ISSUE THREAD

**Issue by WD5Y** [ramdor/Thetis-2.9.0#90]
When starting up Thetis in Collapsed view some of the controls from the Expanded view show up in the lower right corner. If you startup in Expanded view then change to Collapsed view the screen is correct, no extra controls showing; or after startup in the Collapsed view you go from then Collapsed view to Expanded view then back to Collapsed view all is good.

Thanks And 73's
Joe
WD5Y

**Comment by DH1KLM** [comment]
I can confirm this behavior.

**Comment by ramdor** [comment]
fixed, issue with SelectModeDependentPanel()

**Comment by WD5Y** [comment]
Richie,
Thanks for all you are doing with Thetis. This is great!
